Allowing customization of the center frequency and of material layers
agencyenterprise/neurotechdevkit pull request #82
Opened 2023-06-14 19:30 UTC by NewtonSander

This PR allows the configuration of center frequency and also makes it much more simpler to customize the material layers of a simulation

2023-07-03 18:44 UTC, d-lucena commented on src/neurotechdevkit/scenarios/_scenario_1.py
>          speed_water = 1500  # m/s
`c_freq` below is staying constant instead of updating with the user defined value.

2023-07-03 18:44 UTC, d-lucena commented on src/neurotechdevkit/scenarios/_scenario_2.py
> +        self, extent: npt.NDArray[np.float_]
`c_freq` below is staying constant instead of updating with the user defined value.

2023-07-04 16:28 UTC, d-lucena requested changes

2023-07-05 11:26 UTC, NewtonSander commented on docs/examples/plot_customized_center_frequency.py
> +  "tumor": ndk.materials.Material(vp=1850.0, rho=1250.0,alpha=0.8,render_color="#94332F"),
I am adding the linter to the examples folder now

2023-07-17 00:43 UTC, d-lucena approved these changes

2023-07-17 00:43 UTC, d-lucena commented on docs/examples/plot_customized_center_frequency.py
> +# Customizing material properties with random values
```suggestion
# Customizing material properties
```

2023-07-17 05:53 UTC, merged